// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Url struct {
	ID             string
	OriginalUrl    string
	CreatedAt      time.Time
	LastAccessedAt time.Time
	AccessCount    int32
}
