// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: urls.sql

package db

import (
	"context"
	"time"
)

const addURL = `-- name: AddURL :one
INSERT INTO urls (id, original, created_at)
VALUES ($1, $2, $3)
RETURNING id, original, created_at
`

type AddURLParams struct {
	ID        string
	Original  string
	CreatedAt time.Time
}

func (q *Queries) AddURL(ctx context.Context, arg AddURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, addURL, arg.ID, arg.Original, arg.CreatedAt)
	var i Url
	err := row.Scan(&i.ID, &i.Original, &i.CreatedAt)
	return i, err
}

const getID = `-- name: GetID :one
SELECT id FROM urls
WHERE original = $1
`

func (q *Queries) GetID(ctx context.Context, original string) (string, error) {
	row := q.db.QueryRowContext(ctx, getID, original)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOriginalURL = `-- name: GetOriginalURL :one
SELECT original FROM urls
WHERE id = $1
`

func (q *Queries) GetOriginalURL(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOriginalURL, id)
	var original string
	err := row.Scan(&original)
	return original, err
}
